layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects: 
    - Project-Euler
    - Andrew-Ng-s-Machine-Learning-Course-Coursera
    # - repo-name

social_media:
  #behance: your_username
  #dribbble: your_username
  facebook: vibhash1997
  #hackerrank: your_username
  instagram: its_vibhash
  #keybase: your_username
  linkedin: vibhashchandra
  #mastodon: your_username
  #medium: your_username
  #stackoverflow: your_user_id
  #telegram: your_username
  #twitter: your_username
  #unsplash: your_username
  #vk: your_username
  #website: http://your_website_url
  #youtube: your_username

topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Android
    web_url: https://github.com/topics/android
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/android/android.png
    
  - name: C/C++
    web_url: https://github.com/topics/cpp
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/cpp/cpp.png
    
  - name: ML/NLP/DL
    web_url: https://github.com/topics/machine-learning
    image_url: https://www.pngkey.com/png/full/314-3142775_beltech-2018-icons-webside-schedule-machine-learning-machine.png
